"""Plain-language explanations, optionally generated by an on-device LLM.

Default: deterministic, bilingual templates built from the fusion state
(instant, zero power, never hallucinates).

Optional: Llama-3.2-3B-Instruct from Qualcomm AI Hub running on the Hexagon
NPU through the Qualcomm Genie SDK (``genie-t2t-run``). AI Hub publishes
~11 tokens/s and ~0.12 s time-to-first-token for this model on Snapdragon X
Elite, which is fast enough to write a two-sentence warning while the call is
still going. The LLM only rephrases evidence Sajag already found; the verdict
itself always comes from the deterministic fusion engine.
"""

from __future__ import annotations

import logging
import os
import shutil
import subprocess
from pathlib import Path

from .fusion import RiskState

log = logging.getLogger("sajag.explain")

HEADLINES = {
    "danger": ("STOP. This looks like a scam.", "रुकिए! यह धोखाधड़ी लगती है।"),
    "warning": ("Warning: strong signs of a scam.", "चेतावनी: धोखाधड़ी के गंभीर संकेत।"),
    "caution": ("Be careful: some scam signs.", "सावधान: कुछ संदिग्ध संकेत।"),
    "safe": ("No scam signs right now.", "अभी कोई संदिग्ध संकेत नहीं।"),
}


def template_explanation(state: RiskState, lang: str = "en") -> dict:
    head_en, head_hi = HEADLINES[state.level]
    fam = f" ({state.family_name})" if state.family_name else ""
    if lang == "hi":
        return {
            "headline": head_hi,
            "why": state.reasons_hi[:4],
            "advice": state.advice_hi,
            "helpline": "1930 | cybercrime.gov.in",
        }
    return {
        "headline": head_en + fam,
        "why": state.reasons[:4],
        "advice": state.advice,
        "helpline": "1930 | cybercrime.gov.in",
    }


class GenieExplainer:
    """Wraps the Genie SDK text-to-text runner for an AI Hub LLM bundle."""

    def __init__(self, bundle_dir: str | os.PathLike, timeout_s: float = 20.0):
        self.bundle_dir = Path(bundle_dir)
        self.config = self.bundle_dir / "genie_config.json"
        self.exe = shutil.which("genie-t2t-run") or str(self.bundle_dir / "genie-t2t-run.exe")
        self.timeout_s = timeout_s

    def available(self) -> bool:
        return self.config.exists() and Path(self.exe).exists()

    def explain(self, state: RiskState, lang: str = "en") -> str | None:
        if not self.available():
            return None
        language = "simple Hindi" if lang == "hi" else "simple English"
        evidence = "; ".join(state.reasons[:5])
        prompt = (
            "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n"
            "You protect elderly Indian users from phone scams. Reply in two short sentences.<|eot_id|>"
            "<|start_header_id|>user<|end_header_id|>\n\n"
            f"Scam type: {state.family_name or 'unknown'}. Evidence: {evidence}. "
            f"Explain to the user in {language} why this is dangerous and what to do now. "
            "Mention helpline 1930.<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"
        )
        try:
            out = subprocess.run([self.exe, "-c", str(self.config), "-p", prompt], cwd=self.bundle_dir,
                                 capture_output=True, text=True, timeout=self.timeout_s)
        except Exception as exc:  # pragma: no cover - device specific
            log.warning("genie failed: %s", exc)
            return None
        text = out.stdout
        if "[BEGIN]:" in text:
            text = text.split("[BEGIN]:", 1)[1]
        return text.split("[END]", 1)[0].strip() or None
